### PR TITLE
lens-3.8 compatibility

### PR DESCRIPTION
**Pull request by supki**

### CODE REVIEW

**Comment by ocharles** [comment]
Looks good, but you didn't bump the minimum bound in the `.cabal` file.

**Comment by supki** [comment]
Thanks for noticing :)

**Comment by ocharles** [comment]
Perfect! :+1:

**Comment by ocharles** [comment]
@tanakh - ping, could really do with this being released!

**Comment by ekmett** [comment]
We've had multiple people hop in the #haskell-lens channel asking about this patch.

**Comment by tanakh** [comment]
Sorry for late reply.
Thank you for patch!

**Pull request merged**
